
package plagiarismdetectorui;

import java.io.File;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author team-22
 * This class creates a page for the user to upload 2 new files 
 */
public class UploadAndCompare extends javax.swing.JFrame {

    /**
     * Creates new form UploadAndCompare
     */
    //Name of Input File 1
     String fileName1;
     //Name of Input File 2
     String fileName2;
     //HashMap to store file names and their path on file system
     HashMap<String,String> fileMap;
     //For calling functions of Validation class
     Validations validation;
     
     //Constructor
    public UploadAndCompare(HashMap<String,String> fileMap) {
        initComponents();
        initForm();
        this.fileMap = fileMap;
        setFileChooser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //initComponents method is generated by NetBeans when you create a Swing application page/form.
    //Making any changes to this method will make your form uneditable by the GUI
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser1 = new javax.swing.JFileChooser();
        fileChooser2 = new javax.swing.JFileChooser();
        appName = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        helpText = new javax.swing.JLabel();
        fileInput1 = new javax.swing.JTextField();
        fileInput2 = new javax.swing.JTextField();
        browseFile1 = new javax.swing.JButton();
        browseFile2 = new javax.swing.JButton();
        checkSimilarity = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        appName.setBackground(new java.awt.Color(50, 111, 197));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Plagiarism Detector");

        javax.swing.GroupLayout appNameLayout = new javax.swing.GroupLayout(appName);
        appName.setLayout(appNameLayout);
        appNameLayout.setHorizontalGroup(
            appNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appNameLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        appNameLayout.setVerticalGroup(
            appNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        helpText.setText("Upload documents from file system to compare");

        fileInput1.setText("Enter file input 1");
        fileInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileInput1ActionPerformed(evt);
            }
        });

        fileInput2.setText("Enter file input 2");
        fileInput2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileInput2ActionPerformed(evt);
            }
        });

        browseFile1.setText("Browse");
        browseFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseFile1ActionPerformed(evt);
            }
        });

        browseFile2.setText("Browse");
        browseFile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseFile2ActionPerformed(evt);
            }
        });

        checkSimilarity.setText("Calculate similarity score");
        checkSimilarity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSimilarityActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(appName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fileInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(browseFile2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(fileInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(helpText, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(89, 89, 89)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(browseFile1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(77, 77, 77)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(checkSimilarity, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(helpText, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseFile2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(checkSimilarity, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileInput1ActionPerformed
        
    }//GEN-LAST:event_fileInput1ActionPerformed

    private void fileInput2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileInput2ActionPerformed
        
    }//GEN-LAST:event_fileInput2ActionPerformed
//Button to browse input file 1 for file system
    private void browseFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseFile1ActionPerformed
        int returnVal = fileChooser1.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser1.getSelectedFile();
        if(validation.checkFileSize(file)){
           JOptionPane.showMessageDialog(null, UIConstants.EMPTY_FILES_MESSAGE );
            return;
        }
            
        try {
          // What to do with the file, e.g. display it in a TextArea
          fileName1 = file.getAbsolutePath();
          //Check if File is Valid
          	  fileInput1.setText(fileName1);
          	  
        } catch (Exception ex) {
                        Logger.getLogger(PlagiarismResult.class.getName()).log(Level.SEVERE, null, ex);

        }
    } 
    }//GEN-LAST:event_browseFile1ActionPerformed
//Button to browse input file 2 for file system
    private void browseFile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseFile2ActionPerformed
        int returnVal = fileChooser2.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser2.getSelectedFile();
        if(validation.checkFileSize(file)){
                
           	JOptionPane.showMessageDialog(null, UIConstants.EMPTY_FILES_MESSAGE );
            return;
        }
        try {
            String file2Path = file.getAbsolutePath();
          // What to do with the file, e.g. display it in a TextArea
          fileName2 = file.getAbsolutePath();
          //Check if file is valid
          	  fileInput2.setText(fileName2);
          
        } catch (Exception ex) {
                       Logger.getLogger(PlagiarismResult.class.getName()).log(Level.SEVERE, null, ex);

        }
    } 
    }//GEN-LAST:event_browseFile2ActionPerformed
//Calculate Similarity Button
    private void checkSimilarityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSimilarityActionPerformed
        //Check if no file is selected
    		if(fileName1.equals("")){
    			JOptionPane.showMessageDialog(null, UIConstants.INVAILD_FILE1_MESSAGE);
    			return;
    		}
    		else if(fileName2.equals("")){
    			JOptionPane.showMessageDialog(null, UIConstants.INVAILD_FILE2_MESSAGE);
    			return;
    		}
    		//If both files are valid then only calculate similarity
                    
    		new PlagiarismResult(fileName1,fileName2,fileMap,true).setVisible(true);
               this.setVisible(false);
            
            
    }//GEN-LAST:event_checkSimilarityActionPerformed
//Back Button
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
       new Index().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    //Initialize form with some default fields
    private void initForm(){
        fileInput1.setEditable(false);
        fileInput2.setEditable(false);
        fileName1="";
        fileName2="";
        validation = new Validations();
    }
    
    //Add filter to let user select only .java files and directories
    private void setFileChooser(){
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.java", "java");
        fileChooser1.setFileFilter(filter);        
        fileChooser1.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        
        fileChooser2.setFileFilter(filter);        
        fileChooser2.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel appName;
    private javax.swing.JButton backButton;
    private javax.swing.JButton browseFile1;
    private javax.swing.JButton browseFile2;
    private javax.swing.JButton checkSimilarity;
    private javax.swing.JFileChooser fileChooser1;
    private javax.swing.JFileChooser fileChooser2;
    private javax.swing.JTextField fileInput1;
    private javax.swing.JTextField fileInput2;
    private javax.swing.JLabel helpText;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
